[[news]]
date = "2026-06"
content = "Starting my research internship with the awesome team at 4DV Lab at 4DV Lab, ShanghaiTech! let's make some magic! 🚀✨💻"

# [[news]]
# date = "2025-09"
# content = "Starting my PhD at the University of Example"
